# Generated by Django 4.2.3 on 2024-02-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0002_service_postads_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsvideos',
            name='services',
            field=models.ManyToManyField(to='naijahook.service'),
        ),
    ]
