# Generated by Django 4.2.3 on 2024-02-11 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0012_rename_services_postads_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=300)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('reported_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naijahook.adsvideos')),
            ],
        ),
    ]
