# Generated by Django 4.2.3 on 2024-02-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0013_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naijahook.postads'),
        ),
    ]
