# Generated by Django 4.2.3 on 2024-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0016_adsvideos_suspended_postads_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='postads',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
