# Generated by Django 4.2.3 on 2024-02-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0018_verify_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsvideos',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
