# Generated by Django 4.2.3 on 2024-03-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0022_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
