# Generated by Django 4.2.3 on 2024-06-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0024_alter_adsvideos_video_alter_postads_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postads',
            name='video',
        ),
    ]
