# Generated by Django 4.2.3 on 2024-06-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0025_remove_postads_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsvideos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
