# Generated by Django 4.2.3 on 2024-06-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0026_adsvideos_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsvideos',
            name='thumbnail',
        ),
    ]
