# Generated by Django 4.2.3 on 2024-06-28 23:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0028_adsvideos_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsvideos',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='adsvideos',
            name='bio',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='adsvideos',
            name='full_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adsvideos',
            name='shot_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adsvideos',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
