# Generated by Django 4.2.3 on 2024-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0029_remove_adsvideos_thumbnail_alter_adsvideos_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsvideos',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
