# Generated by Django 4.2.3 on 2024-06-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0030_adsvideos_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsvideos',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
