# Generated by Django 4.2.3 on 2024-06-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0031_adsvideos_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsvideos',
            name='service',
        ),
    ]
