# Generated by Django 4.2.3 on 2024-06-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0032_remove_adsvideos_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsvideos',
            name='duration',
        ),
    ]
