# Generated by Django 4.2.3 on 2024-07-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0033_remove_adsvideos_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide2',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide3',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
