# Generated by Django 4.2.3 on 2024-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0034_slide_link_slide2_link_slide3_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postads',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
