# Generated by Django 4.2.3 on 2024-09-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0036_adsvideos_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsvideos',
            name='State',
        ),
        migrations.RemoveField(
            model_name='adsvideos',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='adsvideos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adsvideos',
            name='full_night',
        ),
        migrations.RemoveField(
            model_name='adsvideos',
            name='number',
        ),
        migrations.RemoveField(
            model_name='adsvideos',
            name='shot_time',
        ),
        migrations.RemoveField(
            model_name='adsvideos',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='adsvideos',
            name='whatsapp',
        ),
    ]
