# Generated by Django 4.2.3 on 2024-09-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0037_remove_adsvideos_state_remove_adsvideos_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsvideos',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
