# Generated by Django 4.2.3 on 2024-02-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0005_alter_client_user_alter_escort_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
