# Generated by Django 4.2.3 on 2024-02-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0007_remove_customuser_is_admin_alter_client_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='user',
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='escort',
        ),
    ]
