# Generated by Django 4.2.3 on 2024-02-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0008_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsvideos',
            name='services',
        ),
        migrations.RemoveField(
            model_name='postads',
            name='services',
        ),
        migrations.AddField(
            model_name='adsvideos',
            name='service',
            field=models.ManyToManyField(related_name='videoservices', to='naijahook.service'),
        ),
        migrations.AddField(
            model_name='postads',
            name='service',
            field=models.ManyToManyField(related_name='services', to='naijahook.service'),
        ),
    ]
