# Generated by Django 4.2.3 on 2024-02-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0010_alter_postads_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postads',
            old_name='service',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='services',
        ),
    ]
