# Generated by Django 4.2.3 on 2024-02-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0014_alter_report_reported_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reporter',
            new_name='name',
        ),
    ]
