# Generated by Django 4.2.3 on 2024-02-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0015_rename_reporter_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsvideos',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postads',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
