# Generated by Django 4.2.3 on 2024-02-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0019_adsvideos_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture_With_ID', models.ImageField(upload_to='')),
                ('ID_Front', models.ImageField(upload_to='')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naijahook.adsvideos')),
            ],
        ),
    ]
