# Generated by Django 4.2.3 on 2024-03-06 20:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('naijahook', '0020_verify_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsvideos',
            name='State',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='naijahook.state'),
        ),
        migrations.AlterField(
            model_name='adsvideos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adsvideos',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
